// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustPaletteColors(arg1, arg2) {
  return window['go']['main']['App']['AdjustPaletteColors'](arg1, arg2);
}

export function ApplyBlueprint(arg1) {
  return window['go']['main']['App']['ApplyBlueprint'](arg1);
}

export function ApplyTheme(arg1) {
  return window['go']['main']['App']['ApplyTheme'](arg1);
}

export function CancelBatchProcessing() {
  return window['go']['main']['App']['CancelBatchProcessing']();
}

export function ClearTheme() {
  return window['go']['main']['App']['ClearTheme']();
}

export function ComputeVariables(arg1, arg2, arg3) {
  return window['go']['main']['App']['ComputeVariables'](arg1, arg2, arg3);
}

export function ContrastRatio(arg1, arg2) {
  return window['go']['main']['App']['ContrastRatio'](arg1, arg2);
}

export function DeleteBlueprint(arg1) {
  return window['go']['main']['App']['DeleteBlueprint'](arg1);
}

export function DownloadWallpaper(arg1) {
  return window['go']['main']['App']['DownloadWallpaper'](arg1);
}

export function ExportTheme(arg1) {
  return window['go']['main']['App']['ExportTheme'](arg1);
}

export function ExtractColors(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractColors'](arg1, arg2, arg3);
}

export function GenerateGradient(arg1, arg2) {
  return window['go']['main']['App']['GenerateGradient'](arg1, arg2);
}

export function GeneratePaletteFromColor(arg1) {
  return window['go']['main']['App']['GeneratePaletteFromColor'](arg1);
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetFocusTab() {
  return window['go']['main']['App']['GetFocusTab']();
}

export function GetMediaURL(arg1) {
  return window['go']['main']['App']['GetMediaURL'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTemplateColors() {
  return window['go']['main']['App']['GetTemplateColors']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetWallhavenConfig() {
  return window['go']['main']['App']['GetWallhavenConfig']();
}

export function GetWallpaperTags() {
  return window['go']['main']['App']['GetWallpaperTags']();
}

export function HandleDroppedFiles(arg1) {
  return window['go']['main']['App']['HandleDroppedFiles'](arg1);
}

export function ImportFileDialog(arg1) {
  return window['go']['main']['App']['ImportFileDialog'](arg1);
}

export function IsAetherWpAvailable() {
  return window['go']['main']['App']['IsAetherWpAvailable']();
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function IsOmarchyInstalled() {
  return window['go']['main']['App']['IsOmarchyInstalled']();
}

export function IsWidgetMode() {
  return window['go']['main']['App']['IsWidgetMode']();
}

export function ListBlueprints() {
  return window['go']['main']['App']['ListBlueprints']();
}

export function LoadBlueprint(arg1) {
  return window['go']['main']['App']['LoadBlueprint'](arg1);
}

export function LoadOmarchyThemes(arg1) {
  return window['go']['main']['App']['LoadOmarchyThemes'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadImageAsDataURL(arg1) {
  return window['go']['main']['App']['ReadImageAsDataURL'](arg1);
}

export function ResetState() {
  return window['go']['main']['App']['ResetState']();
}

export function SaveBlueprint(arg1) {
  return window['go']['main']['App']['SaveBlueprint'](arg1);
}

export function SaveDataURLToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveDataURLToFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWallhavenConfig(arg1) {
  return window['go']['main']['App']['SaveWallhavenConfig'](arg1);
}

export function SaveWallpaperTags(arg1) {
  return window['go']['main']['App']['SaveWallpaperTags'](arg1);
}

export function ScanLocalWallpapers() {
  return window['go']['main']['App']['ScanLocalWallpapers']();
}

export function SearchWallhaven(arg1) {
  return window['go']['main']['App']['SearchWallhaven'](arg1);
}

export function SetExtractionMode(arg1) {
  return window['go']['main']['App']['SetExtractionMode'](arg1);
}

export function SetWallhavenAPIKey(arg1) {
  return window['go']['main']['App']['SetWallhavenAPIKey'](arg1);
}

export function StartBatchProcessing(arg1, arg2) {
  return window['go']['main']['App']['StartBatchProcessing'](arg1, arg2);
}

export function ToggleFavorite(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleFavorite'](arg1, arg2, arg3);
}
